spring:
  application:
    name: challenge-blue-orange-api
  main:
    banner-mode: "OFF"

server:
  address: 0.0.0.0
  port: 8080

endpoint:
  base-path: /api/v1/public
  creators:
    path: ${endpoint.base-path}/creators
  creators-notes:
    path: ${endpoint.base-path}/creators/notes
  creator-note:
    path: ${endpoint.base-path}/creators/notes/{id}
  health:
    path: /status

redis:
  host: "localhost"
  port: 12305

marvel:
  api:
    base-url: https://gateway.marvel.com
    key: abcdefg12345