spring:
  application:
    name: challenge-blue-orange-api
  main:
    banner-mode: "OFF"

server:
  address: 0.0.0.0
  port: 8080

endpoint:
  base-path: /api
  creator:
    path: ${endpoint.base-path}/creator