spring:
  application:
    name: challenge-blue-orange-api
  main:
    banner-mode: "OFF"

server:
  address: 0.0.0.0
  port: 8080

redis:
  host: "localhost"
  port: 12305

endpoint:
  base-path: /api
  creator:
    path: ${endpoint.base-path}/creator
  health:
    path: /status

marvel:
  api:
    base-url: https://gateway.marvel.com
    key: abcdefg12345